name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  coverage: xdebug
            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist
            - name: Run PHPStan
              run: vendor/bin/phpstan analyse
            - name: Run PHP CS Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff
            - name: Run PHPUnit
              run: vendor/bin/phpunit --coverage-text

